<?php
// In database/migrations/xxxx_xx_xx_create_assets_table.php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAssetsTable extends Migration
{
    public function up()
    {
        Schema::create('assets', function (Blueprint $table) {
            $table->id();
            $table->string('asset_no')->unique(); // Asset number
            $table->unsignedBigInteger('wo_id')->nullable(); // Foreign key to the production order
            $table->boolean('generated_by_system')->default(false); // Indicates if the asset number was generated by the system
            $table->timestamps();

            // Foreign key constraint to the production orders table
            $table->foreign('wo_id')->references('id')->on('production_orders')->onDelete('cascade');
        });
    }

    public function down()
    {
        Schema::dropIfExists('assets');
    }
}
