<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certificate of Conformance (CoC) - {{ $productionOrder->wo_number }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 30px;
        }

        /* Header Section */
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 2px solid #ccc;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header .company-logo {
            max-width: 150px;
        }

        .header .company-logo img {
            max-width: 100%;
            height: auto;
        }

        .header .company-details {
            text-align: left;
            max-width: 75%;
        }

        h1 {
            text-align: center;
            font-size: 28px;
            margin-top: 20px;
        }

        hr {
            border: none;
            border-top: 1px solid #ccc;
            margin: 20px 0;
        }

        /* Details Section */
        .details {
            margin-bottom: 20px;
            text-align: left;
        }

        .details .entry {
            margin-bottom: 10px;
            display: flex;
        }

        .details .entry strong {
            width: 200px;
            display: inline-block;
            font-weight: bold;
        }

        /* Footer Section */
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 14px;
            color: #555;
        }

        /* Button Section */
        .button-group {
            text-align: center;
            margin-top: 20px;
        }

        .button-group button {
            margin: 0 10px;
            padding: 10px 20px;
            font-size: 14px;
            cursor: pointer;
        }

        /* Print Styles */
        @media print {
            .button-group {
                display: none; /* Hide buttons during print */
            }

            body {
                margin: 10mm;
            }

            .header {
                border-bottom: 1px solid #000;
            }
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
        @if ($settings->logo_path)
        <div class="company-logo">
            <img src="{{ asset('storage/' . $settings->logo_path) }}" alt="Logo">
        </div>
        @endif
        <div class="company-details">
            <p>{{ $settings->company_name ?? 'Your Company Name' }}</p>
            <p>{{ $settings->company_address ?? 'Your Address' }}</p>
            <p>{{ $settings->company_contact ?? 'Your Contact Number' }}</p>
            <p>{{ $settings->company_email ?? 'Your Email Address' }}</p>
        </div>
    </div>

    <!-- Certificate Title and Statement -->
    <h1>Certificate of Conformance</h1>
    <p style="text-align: center;">{{ $settings->coc_statement ?? 'Your COC Statement' }}</p>
    <p style="text-align: center;">Production Order: {{ $productionOrder->wo_number }}</p>

    <!-- Details Section -->
    <div class="details">
        <div class="entry">
            <strong>WO Number:</strong> {{ $productionOrder->wo_number }}
        </div>
        <div class="entry">
            <strong>SO Number:</strong> {{ $productionOrder->so_number }}
        </div>
        <div class="entry">
            <strong>Customer:</strong> {{ $productionOrder->customer }}
        </div>
        <div class="entry">
            <strong>Lot Size:</strong> {{ $productionOrder->lot_size }}
        </div>
        <div class="entry">
            <strong>Fulfilled Quantity:</strong> {{ $productionOrder->quantity_fulfilled }}
        </div>
        <div class="entry">
            <strong>Asset Numbers:</strong> 
            @foreach ($productionOrder->assets as $asset)
                {{ $asset->asset_no }}@if (!$loop->last), @endif
            @endforeach
        </div>
    </div>

    <!-- Footer Section -->
    <div class="footer">
        <p>Generated by: {{ auth()->check() ? auth()->user()->name : 'Unknown User' }}</p>
    </div>

    <!-- Button Group -->
    <div class="button-group">
        <button onclick="window.location.href = '{{ route('production.released') }}';">Back</button>
        <button onclick="window.print();">Print</button>
        <button onclick="window.location.href = '{{ route('production.report.partial_view', ['productionOrder' => $productionOrder->id]) }}';">Download PDF</button>
    </div>
</body>
</html>
