<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Asset extends Model
{
    use HasFactory;

    protected $fillable = [
        'asset_no',
        'wo_id', // Foreign key to ProductionOrder
        'generated_by_system', // Indicate if the asset was generated by the system
    ];

    public function productionOrder()
    {
        return $this->belongsTo(ProductionOrder::class, 'wo_id'); 
    }

    // Relationship to Finished Order
    public function finishedOrder()
    {
        return $this->belongsTo(FinishedOrder::class, 'fo_id');
    }
}
